### ISSUE TITLE
Let archetype work with other remote repos

### ISSUE THREAD

**Issue by alexdarch** [nineinchnick/trino-plugin-archetype#31]
It would be nice to not have this so dependent on GitHub. I am trying to use this for gitlab

**Comment by nineinchnick** [comment]
This is by design, this archetype is supposed to be opinionated. I've got a pr open in Trino to add it there without any CI: https://github.com/trinodb/trino/pull/12929

I'd recommend to fork this repo and replace the CI with something that would work in Gitlab.
