### ISSUE TITLE
how to disable github commit in pom.xml

### ISSUE THREAD

**Issue by zeddit** [nineinchnick/trino-plugin-archetype#32]
I am new to java, and I am using `mvn clean install` or `mvn package` to build my trino plugin. however, the error told me to be `Failed to execute goal io.github.git-commit-id:git-commit-id-maven-plugin:5.0.0:revision (default) on project`. 

I don't need that feature, how could I disable this in pom.xml. I could find nothing related to git-commit-id in the pom.xml.

thanks.

**Comment by nineinchnick** [comment]
Can you include a full stack trace? This is used to populate some fields in the manifest.

**Comment by zeddit** [comment]
mvn archetype:generate -DarchetypeGroupId=pl.net.was -DarchetypeArtifactId=trino-plugin-archetype -DarchetypeVersion=1.15 -DgroupId=com.aitopia -DartifactId=trino-plugin-xdb

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] >>> archetype:3.2.1:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< archetype:3.2.1:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO]
[INFO] --- archetype:3.2.1:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[WARNING] No archetype found in remote catalog. Defaulting to internal catalog
[WARNING] Archetype not found in any catalog. Falling back to central repository.
[WARNING] Add a repository with id 'archetype' in your settings.xml if archetype's repository is elsewhere.
Define value for property 'classPrefix': XDB
Define value for property 'connectorName': xdb
Define value for property 'githubOwner': daizhang
[INFO] Using property: githubOwner = daizhang
Define value for property 'githubRepo': none
[INFO] Using property: groupId = com.aitopia
[INFO] Using property: artifactId = trino-plugin-xdb
Define value for property 'version' 1.0-SNAPSHOT: : 0.1-SNAPSHOT
[INFO] Using property: package = com.aitopia
Confirm properties configuration:
classPrefix: XDB
connectorName: xdb
githubOwner: daizhang
githubOwner: daizhang
githubRepo: none
groupId: com.aitopia
artifactId: trino-plugin-xdb
version: 0.1-SNAPSHOT
package: com.aitopia
 Y: : Y
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: trino-plugin-archetype:1.15
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.aitopia
[INFO] Parameter: artifactId, Value: trino-plugin-xdb
[INFO] Parameter: version, Value: 0.1-SNAPSHOT
[INFO] Parameter: package, Value: com.aitopia
[INFO] Parameter: packageInPathFormat, Value: com/aitopia
[INFO] Parameter: classPrefix, Value: XDB
[INFO] Parameter: package, Value: com.aitopia
[INFO] Parameter: githubOwner, Value: daizhang
[INFO] Parameter: githubRepo, Value: none
[INFO] Parameter: groupId, Value: com.aitopia
[INFO] Parameter: connectorName, Value: xdb
[INFO] Parameter: artifactId, Value: trino-plugin-xdb
[INFO] Parameter: version, Value: 0.1-SNAPSHOT
[WARNING] CP Don't override file /Users/daizhang/Arcana/service/trino/trino-plugin-xdb/.mvn
[WARNING] CP Don't override file /Users/daizhang/Arcana/service/trino/trino-plugin-xdb/.github
[WARNING] Don't override file /Users/daizhang/Arcana/service/trino/trino-plugin-xdb/catalog
[WARNING] Don't override file /Users/daizhang/Arcana/service/trino/trino-plugin-xdb/src/main/java/com/aitopia
[WARNING] Don't override file /Users/daizhang/Arcana/service/trino/trino-plugin-xdb/src/test/java/com/aitopia
[INFO] Project created from Archetype in dir: /Users/daizhang/Arcana/service/trino/trino-plugin-xdb
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.131 s
[INFO] Finished at: 2023-08-10T11:11:18+08:00
[INFO] ------------------------------------------------------------------------

---
mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.aitopia:trino-plugin-xdb >--------------------
[INFO] Building trino-plugin-xdb 0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] ----------------------------[ trino-plugin ]----------------------------
[INFO]
[INFO] --- clean:3.2.0:clean (default-clean) @ trino-plugin-xdb ---
[INFO] Deleting /Users/daizhang/Arcana/service/trino/trino-plugin-xdb/target
[INFO]
[INFO] --- trino:12:check-spi-dependencies (default-check-spi-dependencies) @ trino-plugin-xdb ---
[INFO]
[INFO] --- enforcer:3.3.0:enforce (default) @ trino-plugin-xdb ---
[INFO] Rule 0: org.apache.maven.enforcer.rules.dependency.BannedDependencies passed
[INFO] Rule 1: org.apache.maven.enforcer.rules.BanDuplicatePomDependencyVersions passed
[INFO] Rule 2: org.apache.maven.enforcer.rules.dependency.RequireUpperBoundDeps passed
[INFO] Rule 3: org.apache.maven.enforcer.rules.version.RequireMavenVersion passed
[INFO] Rule 4: org.apache.maven.enforcer.rules.version.RequireJavaVersion passed
[INFO] Rule 5: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion passed
[INFO] Rule 6: org.apache.maven.enforcer.rules.RequirePluginVersions passed
[INFO] Rule 7: org.apache.maven.plugins.enforcer.RestrictImports passed
[INFO] Rule 8: org.apache.maven.plugins.enforcer.RestrictImports passed
[INFO] Rule 9: org.apache.maven.plugins.enforcer.RestrictImports passed
[INFO] Rule 10: org.apache.maven.plugins.enforcer.RestrictImports passed
[INFO] Rule 11: org.apache.maven.plugins.enforcer.RestrictImports passed
[INFO]
[INFO] --- dependency-scope:0.10:check (default) @ trino-plugin-xdb ---
[INFO] No test dependency scope issues found
[INFO]
[INFO] --- license:4.2:check (default) @ trino-plugin-xdb ---
[INFO] Checking licenses...
[INFO]
[INFO] --- checkstyle:3.2.2:check (checkstyle) @ trino-plugin-xdb ---
[INFO] You have 0 Checkstyle violations.
[INFO]
[INFO] --- git-commit-id:5.0.0:revision (default) @ trino-plugin-xdb ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.820 s
[INFO] Finished at: 2023-08-10T11:12:06+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.github.git-commit-id:git-commit-id-maven-plugin:5.0.0:revision (default) on project trino-plugin-xdb: Could not complete Mojo execution...: Error: Could not get HEAD Ref, are you sure you have some commits in the dotGitDirectory? -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by zeddit** [comment]
I am sorry for not knowing some terms in java world. I wonder if I correctly understand the word of the `full stack trace`. If the logs above is not the one you need. I will paste something more.

**Comment by nineinchnick** [comment]
Looks like you're getting a different error now. It says the directory for the new plugin already exists. Please rename it or choose a different name for the new plugin.

**Comment by zeddit** [comment]
I am sorry that I upload the wrong log for the first time. I update it and now it points to the error of git issues. it needs me to have git configured, however I don't have a ci/cd system thus I don't want to push my code every time I build my package.

**Comment by nineinchnick** [comment]
You can use git locally, without pushing it. Even if you don't want to use it at all, you could just initialize the repository, by running `git init`, and forget about it.

**Comment by zeddit** [comment]
I run the `git init` but without any push. however, it gives me the error of `Error: Could not get HEAD Ref, are you sure you have some commits in the dotGitDirectory`. should I commit something to the project.

**Comment by nineinchnick** [comment]
Sounds like you need to make an initial commit, you can commit anything, or even have an empty commit.
